name: linting

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: linting-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: check docs
        uses: ./.github/actions/docs-check

  terraform:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: lint terraform
        uses: ./.github/actions/linting
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  avmfix:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: avmfix
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: avmfix
        uses: ./..github/actions/avmfix

  lintcomplete:
    needs: [docs, terraform, avmfix]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All linting checks passed"
